backend:
  name: github
  repo: hack-along/gridsome-boilerplate

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "event"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
