backend:
  name: github
  repo: hack-along/gridsome-boilerplate

media_folder: "static/uploads/events"
public_folder: "/uploads"

collections:
  - name: "event"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          default: "",
          dateFormat: "YYYY-MM-DD",
          timeFormat: false,
          pickerUtc: true,
        }
      - {
          label: "Date underscore",
          name: "date",
          widget: "datetime",
          default: "",
          date_format: "YYYY-MM-DD",
          time_format: false,
          picker_utc: true,
        }
      - {
          label: "only time",
          name: "timeonly",
          widget: "datetime",
          default: "",
          format: "HH:mm A",
          dateFormat: false,
          timeFormat: true,
        }
      - { label: "Time", name: "time", default: "00:00", widget: "string" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          media_library: { config: { multiple: false } },
        }
      - { label: "Body", name: "body", widget: "markdown" }
